projects:
  Project_1:
    version: 0.1.1
    config_files:
      - path: proj1/.env
        format: dotenv
        filters:
          - expression: .VERSION
      - path: proj1/conf.json
        format: json
        filters:
          - expression: .project.version
      - path: proj1/conf.toml
        format: toml
        filters:
          - expression: .project.version
  Project_2:
    version: 0.1.3
    config_files:
      - path: proj2/conf.xml
        format: xml
        filters:
          - expression: .Project.version
      - path: proj2/conf.yaml
        format: yaml
        filters:
          - expression: .project.version
